pipeline {
	agent any
    environment {
        PATH    = "${PATH}:${getTerraformPath()}"
        CONFIG  = "Environment/DEV/us-east-1/"
    }
    stages{
         stage('terraform init'){
            steps {
                sh """
                    cd ${CONFIG}
                    terraform init -upgrade"""
            }
        }
        // stage('terraform plan'){
        //     steps {
        //         sh """
        //             cd ${CONFIG}
        //             terraform plan"""
        //     }
        // }
        stage('terraform apply'){
            steps {
                sh """
                    cd ${CONFIG}
                    terraform destroy -auto-approve"""
            }
        }
    }
}     


def getTerraformPath(){
    def tfHome= tool name:'terraform-40',type:'terraform'
    return tfHome
}