pipeline {
	agent any
    environment {
        PATH    = "${PATH}:${getTerraformPath()}"
        CONFIG  = "Environment/DEV/us-east-1/"
        ACTION  = "destroy"
        RUNNER  = "Ayanfe"
    }
    stages{
        stage('Initial Deployment Approval'){
              steps {
                script {
                def userInput = input(id: 'confirm', message: 'Start Pipeline?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: true, description: 'Start Pipeline', name: 'confirm'] ])
             }
           }
        }
       stage('terraform init'){
             steps {
                slackSend (color: '#FFFF00', message: "STARTED: Job by ${RUNNER}' ${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                sh """
                    cd ${CONFIG}
                    terraform init -upgrade"""
             }
        }
        stage('terraform plan'){
            steps {
                slackSend (color: '#FFFF00', message: "Starting Terraform Plan: Job by ${RUNNER}' ${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                sh """
                    cd ${CONFIG}
                    terraform plan -out=tfplan -input=false"""
            }
        }
        stage('Final Deployment Approval'){
            steps {
                script{
                    def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: true, description: 'Apply terraform', name: 'confirm'] ])
                }
                slackSend (color: '#FFFF00', message: "Plan Approved by: ${RUNNER}' ${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
        }
        stage('Terraform Final Action'){
            steps {
                script{stage("Performing Terraform ${ACTION}")}
                sh """
                    cd ${CONFIG}
                    terraform ${ACTION} --auto-approve"""
            }
        }
     }
}     


def getTerraformPath(){
    def tfHome= tool name:'terraform-40',type:'terraform'
    return tfHome
}
       


