pipeline {
	agent any
    environment {
        PATH = "${PATH}:${getTerraformPath()}"
    }
    stages{
        //  stage('terraform init'){
        //     steps {
        //         sh """
        //             cd Environment/DEV/us-east-1/
        //             terraform init -upgrade"""
        //     }
        // }
        // stage('terraform plan'){
        //     steps {
        //         sh """
        //             cd Environment/DEV/us-east-1/
        //             terraform plan"""
        //     }
        // }
        stage('terraform apply'){
            steps {
                sh """
                    cd Environment/DEV/us-east-1/
                    terraform destroy -auto-approve"""
            }
        }
    }
}     


def getTerraformPath(){
    def tfHome= tool name:'terraform-40',type:'terraform'
    return tfHome
}